FSPACERFINAL/Models/SpacerCard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FSPACERFINAL.Models
{
    public class SpacerCard
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public bool Active { get; set; }

        #region Horizontal Variables and spacer length
        public int HorizontalGearCaseDeviation { get; set; }
        public int HorizontalCarrierDeviation { get; set; }
        public int Bearing { get; set; }
        public float HMDGear { get; set; }
        public double HorizontalSpacerLength { get; set; } //Will be initialized with the class if needed variables are set.
        #endregion

        #region Vertical Variables and spacer length
        public int VerticalGearCaseDeviation { get; set; }
        public int VerticalCarrierDeviation { get; set; }
        public float GearMount { get; set; }
        public float VMDGear { get; set; }
        public double VerticalSpacerLength { get; set; }
        #endregion

        #region Misc Variables
        [ForeignKey("DriveCard")]
        public string DriveNumber { get; set; }
        [ForeignKey("Operator")]
        public int OperatorID { get; set; }
        public DriveCard Drive { get; set; }
        public Operator Operator { get; set; }
        public DateTime Date { get; set; }
        #endregion

        #region Card Back Variables
        //These are set to nullable because they might or might not be set and they will never be used for calculation
        public float? Backlash { get; set; }
        public float? HorizontalSetting { get; set; }
        public float? IntermediateSetting { get; set; }
        public float? OutputSetting { get; set; }
        public string HelicalGearNumber { get; set; }
        public string HelicalPinionNumber { get; set; }
        #endregion

        static private float[,] DriveConstants = new float[5, 10] { {6.455f, 1.4567f, -.0001f, .0005f, 0, 0, 4.582f, 1.4567f, -.0004f, 0},
                                                                 {8.125f, 1.625f, 0, -.0001f, .0001f, 0, 5.25f, 1.8125f, 0, 0},
                                                                 {10, 2.125f, .0003f, -.0001f, 0, 0, 6, 1.8125f, 0, 0},
                                                                 {11.063f, 1.9375f, 0, 0, 0, 0, 7.4375f, 1.9375f, 0, 0},
                                                                 {11.813f, 1.9375f, 0, 0, 0, 0, 7.4375f, 1.9375f, 0, 0} };

        public static int ModelToInt(string model)
        {
            int modelInt;

            switch (model)
            {
                case "F85":
                    modelInt = 0;
                    break;

                case "F110":
                    modelInt = 1;
                    break;

                case "F135":
                    modelInt = 2;
                    break;

                case "F155":
                    modelInt = 3;
                    break;

                case "F175":
                    modelInt = 4;
                    break;

                default:
                    modelInt = 0;
                    break;
            }

            return modelInt;
        }

        public static double GetHorizontalSpacerLength(int model, float horizontalGearCaseDeviation, float horizontalCarrierDeviation, float bearing, float hMDGear)
        {
            if (model != -1)
            {
                double horizontalSpacerLength = (1000 * (DriveConstants[model, 0] + (horizontalGearCaseDeviation / 1000) - (horizontalCarrierDeviation / 1000) - DriveConstants[model, 1] - (bearing / 1000) - hMDGear - (DriveConstants[model, 4]) - (DriveConstants[0, 2]) + (DriveConstants[model, 3]))) / 1000;

                return Math.Round(horizontalSpacerLength, 3);
            }
            else
            {
                return 0.000;
            }
        }

        public static double GetVerticalSpacerLength(int model, float verticalGearCaseDeviation, float verticalCarrierDeviation, float vMDGear, float gearMount)
        {
            if (model != -1)
            {
                float verticalSpacerLength = (1000 * ((DriveConstants[model, 6]) + (verticalGearCaseDeviation / 1000) - (DriveConstants[model, 7]) - (verticalCarrierDeviation / 1000) - (vMDGear + gearMount) + (DriveConstants[model, 8]))) / 1000;

                return Math.Round(verticalSpacerLength, 3);
            }
            else
            {
                return 0.000;
            }

        }
    }
}

FSPACERFINAL/Controllers/SpacerCardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FSPACERFINAL.Data;
using FSPACERFINAL.Models;
using System.Diagnostics;

namespace FSPACERFINAL.Controllers
{
    public class SpacerCardsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SpacerCardsController(ApplicationDbContext context)
        {
            _context = context;
        }

        
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.SpacerCards.Include(s => s.Drive).Include(s => s.Operator);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: SpacerCards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spacerCard = await _context.SpacerCards
                .Include(s => s.Drive)
                .Include(s => s.Operator)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (spacerCard == null)
            {
                return NotFound();
            }

            return View(spacerCard);
        }

        // GET: SpacerCards/Create
        public IActionResult Create()
        {
            ViewData["DriveNumber"] = new SelectList(_context.DriveCards, "DriveNumber", "DriveNumber");
            ViewData["OperatorID"] = new SelectList(_context.Operators, "ID", "ID");
            return View();
        }

        // POST: SpacerCards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Active,HorizontalGearCaseDeviation,HorizontalCarrierDeviation,Bearing,HMDGear,HorizontalSpacerLength,VerticalGearCaseDeviation,VerticalCarrierDeviation,GearMount,VMDGear,VerticalSpacerLength,DriveNumber,OperatorID,Date,Backlash,HorizontalSetting,IntermediateSetting,OutputSetting,HelicalGearNumber,HelicalPinionNumber")] SpacerCard spacerCard)
        {
            if (ModelState.IsValid)
            {
                _context.Add(spacerCard);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DriveNumber"] = new SelectList(_context.DriveCards, "DriveNumber", "DriveNumber", spacerCard.DriveNumber);
            ViewData["OperatorID"] = new SelectList(_context.Operators, "ID", "ID", spacerCard.OperatorID);
            return View(spacerCard);
        }

        // GET: SpacerCards/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spacerCard = await _context.SpacerCards.SingleOrDefaultAsync(m => m.ID == id);
            if (spacerCard == null)
            {
                return NotFound();
            }
            ViewData["DriveNumber"] = new SelectList(_context.DriveCards, "DriveNumber", "DriveNumber", spacerCard.DriveNumber);
            ViewData["OperatorID"] = new SelectList(_context.Operators, "ID", "ID", spacerCard.OperatorID);
            return View(spacerCard);
        }

        // POST: SpacerCards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Active,HorizontalGearCaseDeviation,HorizontalCarrierDeviation,Bearing,HMDGear,HorizontalSpacerLength,VerticalGearCaseDeviation,VerticalCarrierDeviation,GearMount,VMDGear,VerticalSpacerLength,DriveNumber,OperatorID,Date,Backlash,HorizontalSetting,IntermediateSetting,OutputSetting,HelicalGearNumber,HelicalPinionNumber")] SpacerCard spacerCard)
        {
            if (id != spacerCard.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(spacerCard);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpacerCardExists(spacerCard.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DriveNumber"] = new SelectList(_context.DriveCards, "DriveNumber", "DriveNumber", spacerCard.DriveNumber);
            ViewData["OperatorID"] = new SelectList(_context.Operators, "ID", "ID", spacerCard.OperatorID);
            return View(spacerCard);
        }

        // GET: SpacerCards/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spacerCard = await _context.SpacerCards
                .Include(s => s.Drive)
                .Include(s => s.Operator)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (spacerCard == null)
            {
                return NotFound();
            }

            return View(spacerCard);
        }

        // POST: SpacerCards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var spacerCard = await _context.SpacerCards.SingleOrDefaultAsync(m => m.ID == id);
            _context.SpacerCards.Remove(spacerCard);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SpacerCardExists(int id)
        {
            return _context.SpacerCards.Any(e => e.ID == id);
        }

        public IActionResult Back()
        {
            return View();
        }
        //[HttpPost]
        //public IActionResult Back(SpacerCard spacerback) {

        //   float? Backlash = spacerback.Backlash;
        //   float? HorizontalSetting = spacerback.HorizontalSetting;
        //   float? IntermediateSetting = spacerback.IntermediateSetting;
        //   float? OutputSetting = spacerback.OutputSetting;
        //   string HelicalGearNumber = spacerback.HelicalGearNumber;
        //   string HelicalPinionNumber = spacerback.HelicalPinionNumber;

        //  return View();

        //}

        public IActionResult Front()
        {
            //var list = await _context.DriveCards.Model.ToListAsync();
            //var selectList = list.OrderBy(l => l.Model);
            //ViewData["ModelList"] = selectList;

            List<string> ModelsName = new List<string> { "F85", "F110", "F135", "F155", "F175" };
            ViewData["ModelList"] = new SelectList(ModelsName);

            List<string> GearsName = new List<string> { "BL1349", "BL3051", "BL3048", "BL4593", "BL4596" };
            ViewData["GearList"] = new SelectList(GearsName);


            ViewData["DriveNumber"] = new SelectList(_context.DriveCards, "DriveNumber", "DriveNumber");
            ViewData["OperatorID"] = new SelectList(_context.Operators, "ID", "ID");
            return View();

        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Front([Bind("ID,Active,HorizontalGearCaseDeviation,HorizontalCarrierDeviation,Bearing,HMDGear,HorizontalSpacerLength,VerticalGearCaseDeviation,VerticalCarrierDeviation,GearMount,VMDGear,DriveNumber,OperatorID,Date")] SpacerCard spacerCard)
        {

            if (ModelState.IsValid)
            {
                _context.Add(spacerCard);
                Debug.WriteLine("Test" + spacerCard.DriveNumber);
                Console.WriteLine("Test" + spacerCard.DriveNumber);

                //spacerCard.

                spacerCard.VerticalSpacerLength = SpacerCard.GetVerticalSpacerLength(SpacerCard.ModelToInt("F85"),
                                                                                     spacerCard.VerticalGearCaseDeviation,
                                                                                     spacerCard.VerticalCarrierDeviation,
                                                                                     spacerCard.VMDGear,
                                                                                     spacerCard.GearMount);

                spacerCard.HorizontalSpacerLength = SpacerCard.GetHorizontalSpacerLength(SpacerCard.ModelToInt("F85"),
                                                                                       spacerCard.HorizontalGearCaseDeviation,
                                                                                       spacerCard.HorizontalCarrierDeviation,
                                                                                       spacerCard.Bearing,
                                                                                       spacerCard.HMDGear);

                await _context.SaveChangesAsync();

            }

            return RedirectToAction("Details", spacerCard);

            //ViewData["DriveNumber"] = new SelectList(_context.DriveCards, "DriveNumber", "DriveNumber", spacerCard.DriveNumber);
            //ViewData["OperatorID"] = new SelectList(_context.Operators, "ID", "ID", spacerCard.OperatorID);
            //return View(spacerCard);
        }

        //public async Task<IActionResult> Back(int? id)
        //{

FSPACERFINAL/Views/SpacerCards/Back.cshtml
@model FSPACERFINAL.Models.SpacerViewModel

@{
    ViewData["Title"] = "Back";
}

<h2>Back</h2>

<h4>SpacerCard</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-controller="SpacerCards" asp-action="Back" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>           
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                    </label>
                </div>
            </div>           
            <div class="form-group">
                <label asp-for="Backlash" class="control-label"></label>
                <input asp-for="Backlash" class="form-control" />
                <span asp-validation-for="Backlash" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorizontalSetting" class="control-label"></label>
                <input asp-for="HorizontalSetting" class="form-control" />
                <span asp-validation-for="HorizontalSetting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IntermediateSetting" class="control-label"></label>
                <input asp-for="IntermediateSetting" class="form-control" />
                <span asp-validation-for="IntermediateSetting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OutputSetting" class="control-label"></label>
                <input asp-for="OutputSetting" class="form-control" />
                <span asp-validation-for="OutputSetting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HelicalGearNumber" class="control-label"></label>
                <input asp-for="HelicalGearNumber" class="form-control" />
                <span asp-validation-for="HelicalGearNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HelicalPinionNumber" class="control-label"></label>
                <input asp-for="HelicalPinionNumber" class="form-control" />
                <span asp-validation-for="HelicalPinionNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FSPACERFINAL/Views/SpacerCards/Create.cshtml
@model FSPACERFINAL.Models.SpacerCard

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>SpacerCard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="HorizontalGearCaseDeviation" class="control-label"></label>
                <input asp-for="HorizontalGearCaseDeviation" class="form-control" />
                <span asp-validation-for="HorizontalGearCaseDeviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorizontalCarrierDeviation" class="control-label"></label>
                <input asp-for="HorizontalCarrierDeviation" class="form-control" />
                <span asp-validation-for="HorizontalCarrierDeviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bearing" class="control-label"></label>
                <input asp-for="Bearing" class="form-control" />
                <span asp-validation-for="Bearing" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HMDGear" class="control-label"></label>
                <input asp-for="HMDGear" class="form-control" />
                <span asp-validation-for="HMDGear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VerticalGearCaseDeviation" class="control-label"></label>
                <input asp-for="VerticalGearCaseDeviation" class="form-control" />
                <span asp-validation-for="VerticalGearCaseDeviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VerticalCarrierDeviation" class="control-label"></label>
                <input asp-for="VerticalCarrierDeviation" class="form-control" />
                <span asp-validation-for="VerticalCarrierDeviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GearMount" class="control-label"></label>
                <input asp-for="GearMount" class="form-control" />
                <span asp-validation-for="GearMount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VMDGear" class="control-label"></label>
                <input asp-for="VMDGear" class="form-control" />
                <span asp-validation-for="VMDGear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DriveNumber" class="control-label"></label>
                <select asp-for="DriveNumber" class ="form-control" asp-items="ViewBag.DriveNumber"></select>
            </div>
            <div class="form-group">
                <label asp-for="OperatorID" class="control-label"></label>
                <select asp-for="OperatorID" class ="form-control" asp-items="ViewBag.OperatorID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Backlash" class="control-label"></label>
                <input asp-for="Backlash" class="form-control" />
                <span asp-validation-for="Backlash" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorizontalSetting" class="control-label"></label>
                <input asp-for="HorizontalSetting" class="form-control" />
                <span asp-validation-for="HorizontalSetting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IntermediateSetting" class="control-label"></label>
                <input asp-for="IntermediateSetting" class="form-control" />
                <span asp-validation-for="IntermediateSetting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OutputSetting" class="control-label"></label>
                <input asp-for="OutputSetting" class="form-control" />
                <span asp-validation-for="OutputSetting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HelicalGearNumber" class="control-label"></label>
                <input asp-for="HelicalGearNumber" class="form-control" />
                <span asp-validation-for="HelicalGearNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HelicalPinionNumber" class="control-label"></label>
                <input asp-for="HelicalPinionNumber" class="form-control" />
                <span asp-validation-for="HelicalPinionNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FSPACERFINAL/Views/SpacerCards/Delete.cshtml
@model FSPACERFINAL.Models.SpacerCard

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SpacerCard</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HorizontalGearCaseDeviation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HorizontalGearCaseDeviation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HorizontalCarrierDeviation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HorizontalCarrierDeviation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Bearing)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bearing)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HMDGear)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HMDGear)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HorizontalSpacerLength)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HorizontalSpacerLength)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VerticalGearCaseDeviation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerticalGearCaseDeviation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VerticalCarrierDeviation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerticalCarrierDeviation)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GearMount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GearMount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VMDGear)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VMDGear)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VerticalSpacerLength)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VerticalSpacerLength)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Backlash)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Backlash)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HorizontalSetting)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HorizontalSetting)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IntermediateSetting)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IntermediateSetting)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OutputSetting)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OutputSetting)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HelicalGearNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HelicalGearNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HelicalPinionNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HelicalPinionNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Drive)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Drive.DriveNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Operator)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Operator.ID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-default" >Back to Database</a>
    </form>
</div>

FSPACERFINAL/Views/SpacerCards/Length.cshtml
@model FSPACERFINAL.Models.SpacerCard

@{
    ViewData["Title"] = "Length";
}


<h2>Vertical Spacer Length: @Model.VerticalSpacerLength <br /></h2>
<h2>Horizontal Spacer Length: @Model.HorizontalSpacerLength <br /></h2>

FSPACERFINAL/Views/SpacerCards/SpacerBack.cshtml
@model FSPACERFINAL.Models.TestViewModel


@{
    ViewData["Title"] = "Index";
}





<h2>Index</h2>


<table class="table">
    
        <tr>           
            <th>
                @Html.DisplayNameFor(model => model.Backlash)
            </th>
            <td>
                <input type="text" class="form-control" id="blacklash" asp-for="@Model.Backlash" />
            </td>
            <th>
                @Html.DisplayNameFor(model => model.HorizontalSetting)
            </th>
            <td>
                <input type="text" class="form-control" id="blacklash" asp-for="@Model.HorizontalSetting" />
            </td>
            <th>
                @Html.DisplayNameFor(model => model.IntermediateSetting)
            </th>
            <td>
                <input type="text" class="form-control" id="blacklash" asp-for="@Model.IntermediateSetting" />
            </td>
            <th>
                @Html.DisplayNameFor(model => model.OutputSetting)
            </th>
            <td>
                <input type="text" class="form-control" id="blacklash" asp-for="@Model.OutputSetting" />
            </td>
            <th>
                @Html.DisplayNameFor(model => model.HelicalGearNumber)
            </th>
            <td>
                <input type="text" class="form-control" id="blacklash" asp-for="@Model.HelicalGearNumber" />
            </td>
            <th>
                @Html.DisplayNameFor(model => model.HelicalPinionNumber)
            </th>
            <td>
                <input type="text" class="form-control" id="blacklash" asp-for="@Model.HelicalPinionNumber" />
            </td>
            <th>
                @Html.DisplayNameFor(model => model.Drive)
            </th>
            <td>
                <input type="text" class="form-control" id="blacklash" asp-for="@Model.Drive" />
            </td>
            <th>
                @Html.DisplayNameFor(model => model.Operator)
            </th>
            <td>
                <input type="text" class="form-control" id="blacklash" asp-for="@Model.Operator" />
            </td>
            
        </tr>    
    
</table>

<div>
    <input type="submit" value="submit" class="btn btn-success"/>
</div>